# Usa una versión más reciente de Ubuntu
FROM ubuntu:22.10

# Instalar dependencias del sistema
RUN apt-get update && apt-get install -y \
    wget \
    curl \
    gnupg \
    ca-certificates \
    libglib2.0-0 \
    libnss3 \
    libgconf-2-4 \
    libxss1 \
    libappindicator3-1 \
    libindicator3-0.7 \
    libatk-bridge2.0-0 \
    libgtk-3-0 \
    libasound2 \
    libnspr4 \
    libnss3 \
    libxtst6 \
    libxrandr2 \
    libx11-xcb1 \
    libxcomposite1 \
    libxdamage1 \
    libdbus-1-3 \
    libgdk-pixbuf2.0-0 \
    libsecret-1-0 \
    libgl1-mesa-glx \
    libx11-dev \
    python3-pip \
    python3-dev

# Instalar pip y actualizar
RUN python3 -m pip install --upgrade pip

# Copiar los archivos del proyecto
WORKDIR /app
COPY . /app

# Instalar dependencias de Python
RUN pip install -r requirements.txt

# Instalar Playwright y Chromium
RUN pip install playwright
RUN playwright install --with-deps

# Exponer el puerto de la aplicación
EXPOSE 5000

# Comando para ejecutar el bot de Telegram
CMD ["python", "mz.py"]
